# Generated by Django 3.2.11 on 2022-02-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('users', '0002_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sinf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.sinflar'),
        ),
    ]
